# Generated by Django 5.2 on 2025-05-01 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produccion', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuxiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.TextField(blank=True)),
                ('auxiliar', models.ForeignKey(limit_choices_to={'rol': 'AUXILIAR'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('registro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='produccion.registroproduccion')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroOperario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operario', models.ForeignKey(limit_choices_to={'rol': 'OPERARIO'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('registro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='produccion.registroproduccion')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroRevisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.TextField(blank=True)),
                ('registro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='produccion.registroproduccion')),
                ('revisor', models.ForeignKey(limit_choices_to={'rol': 'REVISOR'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
