# Generated by Django 5.2 on 2025-05-01 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('unidades', models.IntegerField()),
                ('lote', models.CharField(max_length=50)),
                ('dia_codificado', models.IntegerField()),
                ('dia_mes_empaque', models.CharField(max_length=10)),
                ('dia_mes_produccion', models.CharField(max_length=10)),
                ('hora_produccion', models.CharField(max_length=10)),
                ('extension', models.CharField(max_length=20)),
                ('vencimiento', models.DateField()),
                ('golpe', models.IntegerField()),
                ('recorte', models.FloatField()),
                ('peso_verificado', models.BooleanField(default=False)),
                ('vacio_verificado', models.BooleanField(default=False)),
                ('detector_metales_check', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('REG', 'Registrado'), ('REV', 'Revisado'), ('DM', 'Validado por D.M.'), ('FIN', 'Finalizado'), ('OBS', 'Observado')], default='REG', max_length=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.producto')),
                ('tipo_maquina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuracion.maquina')),
                ('tipo_turno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuracion.turno')),
            ],
        ),
    ]
