# Generated by Django 5.2 on 2025-06-29 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=4, null=True, unique=True)),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('day', models.IntegerField(default=0, null=True)),
                ('type', models.CharField(choices=[('CRUDO', 'CRUDO'), ('COCIDO', 'COCIDO')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=4, null=True, unique=True)),
                ('shift', models.CharField(choices=[('MAÑANA', 'MAÑANA'), ('TARDE', 'TARDE'), ('NOCHE', 'NOCHE')], max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=4, null=True, unique=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroR145',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maquina', models.TextField(blank=True)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('unidad_kilos', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('EN_PROCESO', 'EN_PROCESO'), ('FINALIZADO', 'FINALIZADO')], default='PENDIENTE', max_length=20)),
                ('fase', models.CharField(choices=[('OPERARIO', 'OPERARIO'), ('REVISADOR', 'REVISADOR'), ('AUXILIAR', 'AUXILIAR'), ('FINALIZADO', 'FINALIZADO')], default='OPERARIO', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('code', models.CharField(editable=False, max_length=4, null=True, unique=True)),
                ('lote_anio', models.CharField(blank=True, max_length=4, null=True)),
                ('lote_sem', models.CharField(blank=True, max_length=2, null=True)),
                ('lote_dme', models.CharField(blank=True, max_length=10, null=True)),
                ('extension_dia', models.CharField(blank=True, max_length=2, null=True)),
                ('extension_dmp', models.CharField(blank=True, max_length=10, null=True)),
                ('extension_hora', models.TimeField(blank=True, null=True)),
                ('vencimiento', models.DateField(blank=True, null=True)),
                ('golpe', models.IntegerField(default=0, null=True)),
                ('recor', models.CharField(blank=True, max_length=10, null=True)),
                ('peso', models.CharField(blank=True, max_length=10, null=True)),
                ('vacio', models.CharField(blank=True, max_length=10, null=True)),
                ('dm', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_operario', models.DateTimeField(auto_now_add=True)),
                ('fecha_revisador', models.DateTimeField(blank=True, null=True)),
                ('fecha_auxiliar', models.DateTimeField(blank=True, null=True)),
                ('auxiliar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auxiliares', to=settings.AUTH_USER_MODEL)),
                ('operario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operarios', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.producto')),
                ('revisador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisadores', to=settings.AUTH_USER_MODEL)),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.asignacionturno')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TurnoTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=4, null=True, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.turno')),
            ],
        ),
        migrations.AddField(
            model_name='asignacionturno',
            name='turno_trabajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.turnotrabajo'),
        ),
        migrations.AlterUniqueTogether(
            name='asignacionturno',
            unique_together={('turno_trabajo', 'usuario')},
        ),
    ]
