# Generated by Django 5.2 on 2025-06-15 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='day',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
