# Generated by Django 5.2 on 2025-05-14 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maquina',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='codigo',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='turno',
            old_name='hora_fin',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='turno',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='turno',
            old_name='hora_inicio',
            new_name='start_time',
        ),
    ]
