# Generated by Django 5.2 on 2025-06-10 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registror145',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.asignacionturno'),
        ),
    ]
