# Generated by Django 5.2 on 2025-05-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0002_rename_nombre_maquina_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='code',
            field=models.CharField(editable=False, max_length=4, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='turno',
            name='code',
            field=models.CharField(editable=False, max_length=4, null=True, unique=True),
        ),
    ]
