# Generated by Django 5.2 on 2025-05-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0003_maquina_code_turno_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='name',
        ),
        migrations.AddField(
            model_name='turno',
            name='shift',
            field=models.CharField(choices=[('MAÑANA', 'MAÑANA'), ('TARDE', 'TARDE'), ('NOCHE', 'NOCHE')], max_length=20, null=True),
        ),
    ]
