# Generated by Django 5.2 on 2025-05-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0004_remove_turno_name_turno_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='shift',
            field=models.CharField(choices=[('MAÑANA', 'MAÑANA'), ('TARDE', 'TARDE'), ('NOCHE', 'NOCHE')], default='MAÑANA', max_length=20),
            preserve_default=False,
        ),
    ]
