# Generated by Django 5.2 on 2025-05-19 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0005_alter_turno_shift'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroR145',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('unidad_kilos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('EN_PROCESO', 'EN_PROCESO'), ('FINALIZADO', 'FINALIZADO')], default='PENDIENTE', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('lote_anio', models.CharField(max_length=4)),
                ('lote_sem', models.CharField(max_length=2)),
                ('lote_dme', models.CharField(max_length=10)),
                ('extension_dia', models.CharField(max_length=2)),
                ('extension_dmp', models.CharField(max_length=10)),
                ('extension_hora', models.TimeField()),
                ('vencimiento', models.DateField()),
                ('golpe', models.BooleanField(default=False)),
                ('recor', models.BooleanField(default=False)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=6)),
                ('vacio', models.BooleanField(default=False)),
                ('dm', models.BooleanField(default=False)),
                ('fecha_operario', models.DateTimeField(auto_now_add=True)),
                ('fecha_revisador', models.DateTimeField(blank=True, null=True)),
                ('fecha_auxiliar', models.DateTimeField(blank=True, null=True)),
                ('fase', models.CharField(choices=[('OPERARIO', 'OPERARIO'), ('REVISADOR', 'REVISADOR'), ('AUXILIAR', 'AUXILIAR'), ('FINALIZADO', 'FINALIZADO')], default='OPERARIO', max_length=20)),
                ('auxiliar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auxiliares', to=settings.AUTH_USER_MODEL)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.maquina')),
                ('operario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operarios', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.producto')),
                ('revisador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisadores', to=settings.AUTH_USER_MODEL)),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.turno')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
