# Generated by Django 5.2 on 2025-05-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0006_registror145'),
    ]

    operations = [
        migrations.AddField(
            model_name='registror145',
            name='code',
            field=models.CharField(editable=False, max_length=4, null=True, unique=True),
        ),
    ]
