# Generated by Django 5.2 on 2025-05-20 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0007_registror145_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registror145',
            name='fase',
        ),
    ]
