# Generated by Django 5.2 on 2025-05-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0008_remove_registror145_fase'),
    ]

    operations = [
        migrations.AddField(
            model_name='registror145',
            name='fase',
            field=models.CharField(choices=[('OPERARIO', 'OPERARIO'), ('REVISADOR', 'REVISADOR'), ('AUXILIAR', 'AUXILIAR'), ('FINALIZADO', 'FINALIZADO')], default='OPERARIO', max_length=20),
        ),
    ]
