# Generated by Django 5.2 on 2025-05-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0009_registror145_fase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registror145',
            name='dm',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='registror145',
            name='golpe',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='registror145',
            name='peso',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='registror145',
            name='recor',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='registror145',
            name='vacio',
            field=models.CharField(max_length=10),
        ),
    ]
