# Generated by Django 5.2 on 2025-06-02 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0010_alter_registror145_dm_alter_registror145_golpe_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TurnoTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.turno')),
            ],
            options={
                'unique_together': {('fecha', 'turno')},
            },
        ),
        migrations.CreateModel(
            name='AsignacionTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('turno_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.turnotrabajo')),
            ],
            options={
                'unique_together': {('turno_trabajo', 'usuario')},
            },
        ),
    ]
