# Generated by Django 5.2 on 2025-06-02 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0011_turnotrabajo_asignacionturno'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='turnotrabajo',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='asignacionturno',
            name='code',
            field=models.CharField(editable=False, max_length=4, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='turnotrabajo',
            name='code',
            field=models.CharField(editable=False, max_length=4, null=True, unique=True),
        ),
    ]
