# Generated by Django 5.2 on 2025-05-13 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('REVISADOR', 'REVISADOR'), ('AUXILIAR', 'AUXILIAR'), ('SUPERVISOR', 'SUPERVISOR'), ('OPERADOR', 'OPERADOR')], max_length=20),
        ),
    ]
