name: Deploy Django App to DigitalOcean

on:
  push:
    branches:
      - main  # o 'develop', según tu flujo

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Pull and Restart Django App on DigitalOcean
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd backend-rico/
            git pull
            source venv/bin/activate
            pip install -r requirements.txt
            python manage.py migrate --noinput
            python manage.py collectstatic --noinput
            sudo systemctl restart gunicorn
